### PR TITLE
tests (travis): run Knora stack

### LINKED ISSUE #2: Automated E2E Tests
related to https://github.com/dhlab-basel/knora-api-js-lib/issues/48

### PR DESCRIPTION
**Pull request by tobiasschweizer**
closes #2

### CODE REVIEW

**Comment by tobiasschweizer** [comment]
@subotic I got an error:

> Failed to access the server: The target server failed to respond
Makefile:3: recipe for target 'graphdb-se-docker-init-knora-test' failed
make[1]: *** [graphdb-se-docker-init-knora-test] Error 2
make[1]: Leaving directory '/home/travis/build/dasch-swiss/knora-api-js-lib-test/knora-api/webapi/scripts'
Makefile:307: recipe for target 'init-db-test' failed
make: *** [init-db-test] Error 2
travis_time:end:34f46b20:start=1571907393590765685,finish=1571908115892041006,duration=722301275321,event=install
[0K[31;1mThe command "cd knora-api && make stack-up && make init-db-test && make stack-restart" failed and exited with 2 during .[0m

> Your build has been stopped.

"init-db-test" did not work

**Comment by tobiasschweizer** [comment]
@subotic I put in some sleeps ...

**Comment by tobiasschweizer** [comment]
see https://github.com/dasch-swiss/knora-py/blob/wip/add-bazel/.travis.yml

**Review by subotic — APPROVED** [review]
Great, thanks! LGTM :-)

**Pull request merged**
